nelmio_api_doc:
    documentation:
        info:
            title: OYSTERCULT API
            description: API pour la gestion de l'élevage d'huîtres
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    models:
        names:
            - { alias: OysterTable, type: App\Entity\Inventory\OysterTable }
            - { alias: PurificationPool, type: App\Entity\Inventory\PurificationPool }
            - { alias: Supplier, type: App\Entity\Supplier\Supplier }
            - { alias: SupplierProduct, type: App\Entity\Supplier\SupplierProduct }
            - { alias: SupplierOrder, type: App\Entity\Supplier\SupplierOrder }
