version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./public:/var/www/html/public
    depends_on:
      - php
    networks:
      - oystercult

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=prod
    depends_on:
      - mysql
      - redis
    networks:
      - oystercult

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - oystercult

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - oystercult

volumes:
  mysql_data:
  redis_data:

networks:
  oystercult:
    driver: bridge
